### ISSUE TITLE
WPS Office is unusable with dark theme

### ISSUE THREAD

**Issue by teejee2008** [teejee2008/umix-os#11]
Fix for this issue:
Change the exec line in .desktop files.

```
gedit $HOME/.local/share/applications/wps-office-et.desktop
Exec=/usr/bin/et %f -style motif 
```

```
gedit $HOME/.local/share/applications/wps-office-wpp.desktop
Exec=/usr/bin/wpp %f -style motif 
```

```
gedit $HOME/.local/share/applications/wps-office-wps.desktop
Exec=/usr/bin/wps %f -style motif 
```

This fix will be included in next release, so that WPS office looks correct if you install it.

**Comment by andrfgs** [comment]
This results in an error:

> Unable to open "motif"
> This file may have been renamed, deleted or moved

**Comment by bkemmer** [comment]
Hi, I am using KDE on manjaro and applying this command I got this message:
![Screenshot_20200415_102211](https://user-images.githubusercontent.com/7491603/79342006-fa0c6580-7f02-11ea-8049-c52ae70e3aac.png)

Is there another style from kde which I could use?

Thank you in advance, WPS has been the missing piece for linux.

**Comment by teejee2008** [comment]
This fix doesn't work with recent versions of WPS office. Only solution I found was to install WPS from Flatpak. Flatpak version of WPS uses the light theme by default.
`flatpak install flathub com.wps.Office`
